export const gradeNames = [
  {
    name: 'Gem Mint',
    shortname: 'GM',
    score: 10.0,
    value: '10.0',
  },
  {
    name: 'Mint',
    shortname: 'MT',
    score: 9.9,
    value: '9.9',
  },
  {
    name: 'Near Mint / Mint',
    shortname: 'NM/MT',
    score: 9.8,
    value: '9.8',
  },
  {
    name: 'Near Mint +',
    shortname: 'NM+',
    score: 9.6,
    value: '9.6',
  },
  {
    name: 'Near Mint',
    shortname: 'NM',
    score: 9.4,
    value: '9.4',
  },
  {
    name: 'Near Mint -',
    shortname: 'NM-',
    score: 9.2,
    value: '9.2',
  },
  {
    name: 'Very Fine / Near Mint',
    shortname: 'VF/NM',
    score: 9.0,
    value: '9.0',
  },
  {
    name: 'Very Fine +',
    shortname: 'VF+',
    score: 8.5,
    value: '8.5',
  },
  {
    name: 'Very Fine',
    shortname: 'VF',
    score: 8.0,
    value: '8.0',
  },
  {
    name: 'Very Fine -',
    shortname: 'VF-',
    score: 7.5,
    value: '7.5',
  },
  {
    name: 'Fine / Very Fine',
    shortname: 'F/VF',
    score: 7.0,
    value: '7.0',
  },
  {
    name: 'Fine +',
    shortname: 'F+',
    score: 6.5,
    value: '6.5',
  },
  {
    name: 'Fine',
    shortname: 'F',
    score: 6.0,
    value: '6.0',
  },
  {
    name: 'Fine -',
    shortname: 'F-',
    score: 5.5,
    value: '5.5',
  },
  {
    name: 'Very Good / Fine',
    shortname: 'VG/F',
    score: 5.0,
    value: '5.0',
  },
  {
    name: 'Very Good +',
    shortname: 'VG+',
    score: 4.5,
    value: '4.5',
  },
  {
    name: 'Very Good',
    shortname: 'VG',
    score: 4.0,
    value: '4.0',
  },
  {
    name: 'Very Good -',
    shortname: 'VG-',
    score: 3.5,
    value: '3.5',
  },
  {
    name: 'Good / Very Good',
    shortname: 'G/VG',
    score: 3.0,
    value: '3.0',
  },
  {
    name: 'Good +',
    shortname: 'G+',
    score: 2.5,
    value: '2.5',
  },
  {
    name: 'Good',
    shortname: 'G',
    score: 2.0,
    value: '2.0',
  },
  {
    name: 'Good -',
    shortname: 'G-',
    score: 1.8,
    value: '1.8',
  },
  {
    name: 'Fair / Good',
    shortname: 'F/G',
    score: 1.5,
    value: '1.5',
  },
  {
    name: 'Fair',
    shortname: 'F',
    score: 1.0,
    value: '1.0',
  },
  {
    name: 'Poor',
    shortname: 'P',
    score: 0.5,
    value: '0.5',
  },
];
